spring.config.import=optional:classpath:.env.properties
spring.application.name=aiservice

spring.mongodb.uri=${spring.mongodb.uri}
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=activity-processor-group
kafka.topic.name=activity-events
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=com.fitness.aiservice.model.Activity
spring.kafka.consumer.properties.spring.json.trusted.packages=*
gemini.api.url=${gemini.api.url}
gemini.api.key=${gemini.api.key}
server.port=8083